# Базовий образ на Alpine
FROM node:20-alpine

# Робоча директорія всередині контейнера
WORKDIR /app

# Копіюємо тільки файли package.json і встановлюємо залежності
COPY package*.json ./
RUN npm install

# Копіюємо увесь код
COPY . .

# Вказуємо порт (не обов’язково, але рекомендовано)
EXPOSE 3000

# Команда запуску
CMD ["node", "index.js"]
